// Question deck for WRNS-lite
// 13 themes × ~5–27 questions each = ~150 prompts.
// Every card shows the theme + question in both zh & en simultaneously.

export const THEMES = [
  { id: "self",      zh: "自我認識", en: "About You" },
  { id: "interests", zh: "興趣",     en: "Hobbies" },
  { id: "food",      zh: "食物",     en: "Food" },
  { id: "daily",     zh: "日常",     en: "Daily Life" },
  { id: "travel",    zh: "旅行",     en: "Travel" },
  { id: "culture",   zh: "文化",     en: "Culture" },
  { id: "childhood", zh: "童年",     en: "Childhood" },
  { id: "love",      zh: "感情",     en: "Love" },
  { id: "growth",    zh: "成長",     en: "Growth" },
  { id: "emotions",  zh: "情緒",     en: "Emotions" },
  { id: "values",    zh: "價值觀",   en: "Values" },
  { id: "social",    zh: "社群",     en: "Social Media" },
  { id: "dreams",    zh: "夢想",     en: "Dreams" },
];

export const QUESTIONS = {
  zh: {
    self: [
      "你的中/英名字有什麼特別的故事嗎?",
      "介紹一下你的家鄉,有沒有什麼是你很喜歡 / 很不喜歡的?",
      "你會怎麼用三個詞形容自己?",
      "你的星座是什麼?有什麼特質?你相信星座嗎?",
      "熟了以後,別人會發現你跟第一印象有什麼不同?",
      "你目前就讀什麼科系或從事什麼工作?當初為什麼選擇這個科系?你喜歡嗎?",
      "你最近生活中最常做的事情是什麼?",
      "最近有什麼事情讓你很期待?",
      "來參加語伴計畫有想得到或學到什麼嗎?",
      "你身上有沒有一個很容易被記住的特點?",
      "有加入過什麼社團嗎?為什麼會想加入呢?",
      "你的 MBTI 是什麼?你覺得 MBTI 測得準嗎?",
      "你在人群中通常扮演什麼角色?",
      "你最擅長跟什麼類型的人聊天?",
      "你最不擅長做什麼樣的自我介紹?",
      "你認為自己最大的優點是什麼?",
      "在同儕眼裡,你通常是一個什麼樣的人?",
      "你對於目前生活的狀態喜歡嗎?最近有想要努力改善什麼?",
      "你大學到目前為止,印象最深刻的一天是什麼?",
      "你最近一年做過最衝動、但不後悔的事情是什麼?",
      "在大學時期,參加過最難忘的活動,或最難忘的事情是?",
      "你參加活動時遇過最尷尬或最好笑的事情是什麼?",
      "你覺得你自己是自信還是自卑的人呢?還是都不是?",
      "你有沒有曾經為了融入別人而改變自己?",
      "你是比較理性腦還是感性腦?",
      "你是派對咖,還是喜歡宅在家?",
      "你今天的心情可以用一個顏色形容,是什麼顏色?",
      "分享一件關於你、但大多數人都不知道的事。例如某些獨特的經歷。",
      "你多久回家一次? 你是會想家的人嗎？",
      "你最喜歡春、夏、秋、冬哪一個季節?為什麼?",
      "你比較喜歡下雨天的寧靜,還是晴天烈日下的熱情與活力?",
      "除了中英文以外,你還會哪些語言?",
      "你覺得學習一個語言最困難的是哪一部分?例如聽、說、讀、寫。",
    ],
    interests: [
      "你比較喜歡動態活動還是靜態活動?平常最常做的休閒活動是什麼?",
      "平常喜歡看 YouTube 或刷短影音嗎?有沒有喜歡的網紅?",
      "你最喜歡哪一種音樂?有沒有最喜歡的歌手呢?",
      "你最喜歡的一部電影是什麼?",
      "最近看過最好看的影集是什麼?",
      "喜歡看動漫嗎?有沒有你最欣賞的動漫人物?你喜歡他什麼特質?",
      "你喜歡看書嗎?有哪一本書影響你很深?",
      "最喜歡看或參與哪一種運動?",
      "你喜歡拍照嗎?",
      "你比較喜歡拍風景、食物還是人物?",
      "你有收藏什麼東西嗎?",
      "有什麼興趣是你一直很想開始,卻還沒開始的?",
      "你小時候的興趣和現在一樣嗎?",
      "你最願意花錢在哪一種興趣上?",
      "有沒有一個冷門興趣是你很喜歡或未來想去試試看的?",
      "你是貓派還是狗派?",
    ],
    food: [
      "你最喜歡吃什麼?最不能接受什麼食物?",
      "香菜可以加嗎?",
      "咖哩飯拌還是不拌?",
      "披薩上可以放鳳梨嗎?",
      "火鍋可以加芋頭嗎?",
      "珍珠奶茶通常喝幾分糖?幾分冰?",
      "對於泰式的辣能接受到什麼程度?",
      "有什麼食物是你小時候討厭,長大後卻喜歡的?",
      "有什麼食物你永遠不可能接受?",
      "你最想推薦外國朋友吃哪一道家鄉的食物?",
      "有哪一道外國料理是你最想嘗試的?",
      "講述一下你吃過最奇耙的一道食物。",
      "旅行時,你願意嘗試當地看起來很有趣但是賣相不好的食物嗎?",
      "你會自己做菜嗎?喜歡叫外送還是自己煮?",
    ],
    daily: [
      "你通常幾點睡?是早起型還是夜貓型?",
      "你會賴床嗎?鬧鐘通常設幾個?有用嗎?",
      "你會對手機電量焦慮嗎?低於多少會去充電?",
      "你平常一天大約使用手機多久?有科技冷漠嗎?",
      "你房間通常整齊嗎?你是亂中有序,還是真的很亂?",
      "出門通常會提早到還是壓線到?你可以接受別人遲到多久?",
      "作業通常是出來就交還是壓線交?",
      "你喜歡有計畫的生活,還是隨性一點?",
      "你最喜歡星期幾?為什麼?",
      "你會通宵嗎?通宵後會精力充沛還是想倒頭就睡?",
    ],
    travel: [
      "你去過最喜歡的地方是哪裡?如果可以再去一次,你最想重訪哪個地方?",
      "你旅行時會把行程、住宿都事先規劃好,還是到了當地再隨機應變?",
      "如果預算有限,你會把錢花在飯店、美食、景點,還是特別的體驗上?",
      "你旅行中遇過最狼狽、最好笑,或最難忘的一次意外是什麼?",
      "如果現在可以免費去任何國家旅行,你會去哪裡、和誰一起去,或是一個人獨旅呢?",
    ],
    culture: [
      "你覺得自己的文化最特別的是什麼?",
      "你最喜歡自己國家的哪一個節日?",
      "打招呼時,你習慣揮手、握手、擁抱還是點頭?",
      "你覺得台灣人在習慣上跟澳洲人最大不同的是什麼?去台灣或澳洲有沒有哪一件事讓你特別驚訝或不習慣?",
      "你覺得外國人對台灣最大的誤解是什麼?",
      "有什麼外國當地的文化習慣是你第一次知道時很驚訝的?",
      "你覺得哪一個國家的生活方式最吸引你?還是自己的國家比較好?",
      "你覺得家庭在個人選擇中應該有多大影響?",
      "你能接受成年後仍和父母同住嗎?",
      "在你的文化中,談戀愛容易嗎?",
    ],
    childhood: [
      "你小時候最喜歡的卡通或零食是什麼?",
      "你小時候最想成為什麼樣的人?現在的你和當時想像的一樣嗎?",
      "你童年最開心或最難忘的一段回憶是什麼?",
      "你小時候的個性和現在差很多嗎?哪一點改變最大?",
      "你認為你童年帶有遺憾嗎?例如可能少做了某些事情?",
    ],
    love: [
      "你比較相信一見鍾情,還是相處久了才慢慢喜歡上對方?",
      "你最容易被一個人的哪種特質吸引?例如幽默、溫柔、自信或有才華?",
      "對方做什麼小事,最容易讓你覺得很貼心或有點心動?",
      "你理想中的第一次約會會去哪裡、做什麼?",
      "你覺得兩個人談戀愛時,有共同興趣比較重要,還是個性互補比較重要?",
      "以你來說,單身是因為還沒遇到適合的人,還是因為享受一個人的生活?",
      "你覺得分手後還能和前任當朋友嗎?還是最好完全不聯絡?",
      "你會希望另一半跟自己家人相處得好嗎?家人的意見對你選擇對象的影響有多大?",
    ],
    growth: [
      "你最近一次走出舒適圈是什麼時候?當時做了什麼,又有什麼感受?",
      "你曾經歷過哪一次失敗或低潮,後來反而讓你更了解自己?",
      "你現在最想培養哪一項能力,或改掉哪一個習慣?為什麼?",
      "如果可以對一年前的自己說一句話,你會說什麼?",
      "你會想交換學生嗎?如果可以的話,最想去哪個國家交換?",
    ],
    emotions: [
      "最近哪一件事最讓你感到壓力?你通常怎麼讓自己放鬆?",
      "當你心情不好時,你比較希望自己獨處,還是有人陪在身邊?",
      "當你向別人分享煩惱時,你希望對方給你建議,還是只要認真聽你說?",
      "你通常會直接表達自己的不開心,還是先假裝沒事、自己慢慢消化?",
      "當你心情不好的時候，去什麼地方或做什麼事情，最容易讓你重新放鬆下來？",
    ],
    values: [
      "對你來說,成功是什麼?",
      "對於一餐來說，價格多少會覺得合理？",
      "對你來說,人生的意義是什麼?",
      "高薪和興趣,你會選哪一個?",
      "天賦和努力哪一個更重要?",
      "如果誠實說出來可能會傷害朋友,但繼續忍耐又會讓你越來越不舒服,你會選擇坦白、用善意的謊言維持關係,還是選擇疏離?",
      "你認為人生需要明確目標嗎?你會因為沒有目標而失去動力嗎?",
      "你的夢想是什麼?你會為了追求夢想而捨去一切嗎?",
      "你覺得選擇比努力重要嗎?",
      "一個人應該追求平凡幸福,還是卓越成就?",
      "你認為人生有標準答案嗎?",
    ],
    social: [
      "你一天大概會用幾個小時的手機?會不會常常覺得只是滑一下,結果時間就不知不覺過去了?",
      "你會在社群媒體展示真實生活嗎?",
      "你會刪除按讚很少的貼文嗎?",
      "你會在意別人有沒有看你的限時動態嗎?",
      "你會偷偷看喜歡的人的舊貼文嗎?",
      "多久沒回訊息算太久?已讀不回對你來說是什麼?",
      "你認為社群媒體的存在讓你的社交生活變得更怡然自得,還是反而讓面對面的互動更稀少?",
      "你會用 AI 完成作業嗎?你覺得 AI 會讓人更聰明還是更依賴?",
      "你有在準備考試期間還是想看社群媒體的困擾嗎?",
    ],
    dreams: [
      "你會選擇一個億,還是清華北大?",
      "如果明天整天完全沒有課、工作和責任,你會從早到晚怎麼安排?",
      "如果你要在一座荒島住三個月,只能帶三樣東西,你會帶什麼?",
      "如果你可以永久刪除一段記憶,你會選擇刪掉它嗎?",
      "如果你確定明天是世界末日,你會選擇做哪些事?",
      "如果可以擁有一種超能力,但只能在日常生活中使用,你會選什麼?你會怎麼用?",
      "如果只能問十年後的自己一個問題,你會問什麼?",
      "如果你的人生是一部兩小時的電影,你覺得現在演到開頭、轉折、低潮還是高潮?目前這一幕在發生什麼?",
    ],
  },
  en: {
    self: [
      "Is there a story behind your Chinese / English name?",
      "Tell us about your hometown — anything you really love or really dislike about it?",
      "How would you describe yourself in three words?",
      "What's your zodiac sign? What traits come with it? Do you believe in astrology?",
      "Once people get to know you, how do you differ from the first impression?",
      "What's your major or job? Why did you pick it — and do you enjoy it?",
      "What do you spend most of your time doing these days?",
      "What are you looking forward to lately?",
      "What do you hope to get or learn out of the language partner program?",
      "Is there something about you that people easily remember?",
      "Have you joined any clubs? What drew you to them?",
      "What's your MBTI? Do you think MBTI is actually accurate?",
      "What role do you usually play in a group?",
      "What kind of person is easiest for you to talk to?",
      "What kind of self-introduction do you find hardest to give?",
      "What do you think is your biggest strength?",
      "In your peers' eyes, what kind of person are you?",
      "Do you like your current life? Anything you're trying to improve lately?",
      "What's been the most memorable day of your university life so far?",
      "What's the most impulsive thing you've done in the past year that you don't regret?",
      "What's the most unforgettable event or moment of your college years?",
      "What's the most awkward or funniest thing that's happened to you at an event?",
      "Would you call yourself confident, self-doubting, or somewhere else entirely?",
      "Have you ever changed yourself just to fit in?",
      "Are you more head or heart?",
      "Party person or stay-at-home person?",
      "What color would your mood today be?",
      "Share something about you that most people don't know — a unique experience, anything.",
      "How often do you go home? Are you someone who misses home?",
      "Spring, summer, fall, or winter — which season do you love most, and why?",
      "Do you prefer the calm of a rainy day, or the warmth and energy of a sunny one?",
      "Besides Chinese and English, what other languages do you know?",
      "What part of learning a language is hardest for you — listening, speaking, reading, or writing?",
    ],
    interests: [
      "Do you prefer active or quiet activities? What's your usual go-to hobby?",
      "Do you watch YouTube or scroll short videos? Any favorite creators?",
      "What kind of music do you love most? A favorite artist?",
      "What's your favorite movie?",
      "What's the best show you've watched recently?",
      "Into anime? Any anime character you admire — and what about them draws you in?",
      "Do you read? Any book that has shaped you deeply?",
      "What's your favorite sport to watch or play?",
      "Do you enjoy taking photos?",
      "Do you prefer photographing landscapes, food, or people?",
      "Do you collect anything?",
      "Is there a hobby you've always wanted to start but haven't?",
      "Are your childhood hobbies the same as now?",
      "Which hobby would you most willingly spend money on?",
      "Is there a niche hobby you love, or want to try someday?",
      "Cat person or dog person?",
    ],
    food: [
      "What's your favorite food? What can you absolutely not eat?",
      "Cilantro — yes or no?",
      "Mix the curry rice, or eat it separately?",
      "Pineapple on pizza — acceptable?",
      "Taro in hot pot — yes or no?",
      "How sweet do you order your bubble tea? Ice level?",
      "How much Thai spice can you handle?",
      "Any food you hated as a kid but love now?",
      "Is there a food you'll never accept?",
      "Which local dish would you most recommend to a foreign friend?",
      "Which foreign dish do you most want to try?",
      "Tell us about the weirdest thing you've ever eaten.",
      "While travelling, would you try something interesting but ugly-looking?",
      "Do you cook? Delivery or homemade?",
    ],
    daily: [
      "When do you go to sleep? Early bird or night owl?",
      "Do you hit snooze? How many alarms do you set — do they actually work?",
      "Do you get phone-battery anxiety? At what % do you start charging?",
      "How long do you use your phone in a day? Any tech burnout?",
      "Is your room tidy? \"Organized chaos\" or actual chaos?",
      "Do you arrive early or right at the deadline? How late can others be before it bothers you?",
      "Do you finish assignments early, or right at the deadline?",
      "Do you prefer a planned life or a spontaneous one?",
      "What's your favorite day of the week? Why?",
      "Do you ever pull all-nighters? Afterwards — wired or wrecked?",
    ],
    travel: [
      "What's the favorite place you've been to? If you could go again, where would you most want to revisit?",
      "Before a trip, do you plan everything — itinerary and hotels — or just play it by ear when you arrive?",
      "On a tight budget, would you spend on hotels, food, sights, or unique experiences?",
      "What's the most embarrassing, funniest, or most unforgettable mishap you've had while travelling?",
      "If you could fly anywhere in the world for free right now — where would you go, who with, or would you go alone?",
    ],
    culture: [
      "What's the most special thing about your own culture?",
      "What's your favorite holiday from your country?",
      "When greeting, do you wave, shake hands, hug, or nod?",
      "What's the biggest habit difference between Taiwanese and Australian people? Did anything in either country surprise you or feel uncomfortable?",
      "What's the biggest misconception foreigners have about Taiwan?",
      "What foreign custom surprised you most when you first heard of it?",
      "Whose lifestyle attracts you most — or is your own country still the best?",
      "How much influence should family have on personal choices?",
      "Could you live with your parents as an adult?",
      "In your culture, is dating easy?",
    ],
    childhood: [
      "What was your favorite cartoon or snack as a kid?",
      "Who did you want to become as a kid? Are you that person now?",
      "What's your happiest or most unforgettable childhood memory?",
      "Is your childhood personality very different from now? What changed most?",
      "Do you carry regrets from childhood — things you wish you had done?",
    ],
    love: [
      "Love at first sight, or slow burn?",
      "Which trait draws you in most — humor, gentleness, confidence, or talent?",
      "What small thing makes you feel cared for, or makes your heart flutter?",
      "What's your ideal first date — where and what?",
      "In a relationship, do shared interests matter more, or complementary personalities?",
      "For you — single because you haven't met the right person, or because you enjoy being alone?",
      "Can you be friends with an ex, or is no contact best?",
      "Would you want your partner to get along with your family? How much does your family's opinion sway who you'd date?",
    ],
    growth: [
      "When did you last step out of your comfort zone? What did you do, and how did it feel?",
      "What failure or low point ended up teaching you about yourself?",
      "What skill do you most want to build, or habit to drop — and why?",
      "If you could say one sentence to your one-year-ago self, what would it be?",
      "Would you do an exchange program? Where would you go?",
    ],
    emotions: [
      "What's stressing you most lately? How do you usually unwind?",
      "When you're down, do you prefer to be alone or have someone with you?",
      "When you share your worries, do you want advice — or just to be heard?",
      "Do you express unhappiness directly, or pretend you're fine and digest it alone?",
      "When you're feeling down, what place or activity helps you relax the most?",
    ],
    values: [
      "What does success mean to you?",
      "For a meal, what price feels reasonable to you?",
      "What gives life meaning for you?",
      "High salary or passion — which would you pick?",
      "Talent or effort — which matters more?",
      "If telling the truth might hurt a friend, but holding back is hurting you — would you be honest, tell a kind lie, or quietly drift apart?",
      "Do you think life needs clear goals? Do you lose motivation without them?",
      "What's your dream? Would you give up everything to chase it?",
      "Do you think choice matters more than effort?",
      "Should one chase ordinary happiness or extraordinary achievement?",
      "Do you think life has a right answer?",
    ],
    social: [
      "How many hours a day do you spend on your phone? Ever feel like you just open it for a sec — and somehow hours are gone?",
      "Do you show your real life on social media?",
      "Do you delete posts that don't get many likes?",
      "Do you care if people view your stories?",
      "Have you secretly scrolled through a crush's old posts?",
      "How long without a reply is too long? What does \"left on read\" mean to you?",
      "Has social media made your social life richer, or replaced face-to-face contact?",
      "Do you use AI for homework? Does AI make people smarter, or more dependent?",
      "Do you still feel the pull of social media during exam season?",
    ],
    dreams: [
      "100 million yuan, or admission to Tsinghua / Peking (China's top universities) — which would you pick?",
      "If tomorrow you had no class, work, or responsibilities — how would you spend the whole day?",
      "Three months on a deserted island — what three things would you bring?",
      "If you could permanently delete one memory, would you?",
      "If you knew the world ended tomorrow, what would you do?",
      "If you could have a superpower, but only for daily life — what would it be, and how would you use it?",
      "If you could ask your 10-years-from-now self one question, what would it be?",
      "If your life were a 2-hour movie, are you at the opening, turning point, low point, or climax? What's happening in this scene?",
    ],
  },
};

// Pool of paired bilingual questions — zh & en at the same index match in meaning.
export function flattenPool() {
  const out = [];
  THEMES.forEach((theme) => {
    const zhArr = QUESTIONS.zh[theme.id] || [];
    const enArr = QUESTIONS.en[theme.id] || [];
    const n = Math.min(zhArr.length, enArr.length);
    for (let i = 0; i < n; i++) {
      out.push({
        id: `${theme.id}-${i}`,
        themeId: theme.id,
        zh: zhArr[i],
        en: enArr[i],
      });
    }
  });
  return out;
}

export function themeLabels(themeId) {
  const t = THEMES.find((x) => x.id === themeId);
  if (!t) return { zh: "", en: "" };
  return { zh: t.zh, en: t.en };
}

export function pickQuestion(usedIds = []) {
  const pool = flattenPool();
  const available = pool.filter((q) => !usedIds.includes(q.id));
  if (available.length === 0) {
    return pool[Math.floor(Math.random() * pool.length)];
  }
  return available[Math.floor(Math.random() * available.length)];
}
